[package]
name = "zene-cloud-git-broker"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile = "3"
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
zene-cloud-db.workspace = true
zene-cloud-domain.workspace = true
zene-cloud-github.workspace = true

[dev-dependencies]
tokio = { workspace = true }
