[package]
name = "zene-cloud-api"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "zene-cloud-api"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
axum.workspace = true
chrono.workspace = true
clap.workspace = true
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
walkdir = "2"
zene-cloud-db.workspace = true
zene-cloud-domain.workspace = true
zene-cloud-git-broker.workspace = true
zene-cloud-github.workspace = true
