[package]
name = "zene-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "zene"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
clap.workspace = true
parking_lot.workspace = true
rustyline.workspace = true
tokio.workspace = true
tokio-util.workspace = true
ctrlc.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde_json.workspace = true
uuid.workspace = true
zene-config = { workspace = true }
zene-core = { workspace = true }
zene-sandbox = { workspace = true }
zene-session = { workspace = true }
zene-llm = { workspace = true }
zene-mcp = { workspace = true }
llm_providers = { workspace = true }
